module.exports = {
    ci: {
        "assert": {
            "preset": "lighthouse:no-pwa",
            "assertions": {
                "categories:performance": ["pessimistic"],
                "categories:accessibility": ["pessimistic"],
                // WCAG 2.1 AA compliance audits
                'accesskeys': ['error'],
                'aria-allowed-attr': ['error'],
                'aria-required-attr': ['error'],
                'aria-required-children': ['error'],
                'aria-required-parent': ['error'],
                'aria-roles': ['error'],
                'aria-valid-attr-value': ['error'],
                'aria-valid-attr': ['error'],
                'audio-caption': ['error'],
                'button-name': ['error'],
                'bypass': ['error'],
                'color-contrast': ['error'],
                'definition-list': ['error'],
                'dlitem': ['error'],
                'document-title': ['error'],
                'duplicate-id': ['error'],
                'frame-title': ['error'],
                'html-has-lang': ['error'],
                'html-lang-valid': ['error'],
                'image-alt': ['error'],
                'input-image-alt': ['error'],
                'label': ['error'],
                'layout-table': ['error'],
                'link-name': ['error'],
                'list': ['error'],
                'listitem': ['error'],
                'meta-refresh': ['error'],
                'meta-viewport': ['error'],
                'object-alt': ['error'],
                'tabindex': ['error'],
                'td-headers-attr': ['error'],
                'th-has-data-cells': ['error'],
                'valid-lang': ['error'],
                'video-caption': ['error'],
                'video-description': ['error'],
                // WCAG 2.1 AA Manual audits
                // these are set to off since these audits must be done manually but keeping them here as a reminder that they need to be done
                'logical-tab-order': "off",
                'focusable-cofftrols': "off",
                'interactive-element-affordance': "off",
                'managed-focus': "off",
                'focus-traps': "off",
                'custom-cofftrols-labels': "off",
                'custom-cofftrols-roles': "off",
                'visual-order-follows-dom': "off",
                'offscreen-cofftent-hidden': "off",
                'heading-levels': "off",
                'use-landmarks': "off",
            },
        },
        collect: {
            staticDistDir: './dist',
            url: ['http://localhost:8080'],
            settings: {
                disableStorageReset: false,
                throttlingMethod: 'devtools',
                chromeFlags: ['--no-sandbox --ignore-certificate-errors']
              },
        },
        upload: {
            target: 'filesystem'
        }, 
    },
};